default:
  image: node:latest

pages:
  cache:
    paths:
    - node_modules/
  script:
    - yarn install
    - yarn run build
    - rm -rf public
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - master
